# Generated by Django 5.0 on 2024-01-03 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cartype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.cartype', verbose_name='Car Type'),
        ),
    ]
