# Generated by Django 5.0 on 2024-01-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_reservation_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='available_car_types',
            field=models.ManyToManyField(to='core.cartype', verbose_name='Available Car Types'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='car_registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Car Registration Number'),
        ),
    ]
