# Generated by Django 5.0 on 2024-01-02 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_companyreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreview',
            name='reservation',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.reservation', verbose_name='Reservation'),
            preserve_default=False,
        ),
    ]
